package InnerClass;
abstract class Person{ 
	int x;
	abstract void eat();  
}
public class AnonymousInner {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Person p=new Person(){
			int val=10;
			void eat(){System.out.println("nice fruits "+ x);}  
		};  
		p.eat();   

	}

}

//Internal class generated by the compiler
//
//import java.io.PrintStream;  
//static class TestAnonymousInner$1 extends Person  
//{  
//   TestAnonymousInner$1(){}  
//   void eat()  
//    {  
//        System.out.println("nice fruits");  
//    }  
//}